version: "3.2"

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/data/application/init.sql
      - ./db/new_config.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always
    expose:
      - '3306'
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
 
  kaught:
    build: ./kaught
    volumes:
      - ./kaught:/code
    depends_on: 
      - db
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_DATABASE}


volumes:
    db-data:
